// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
)

const eventSuppressed = `-- name: EventSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM events
    WHERE monitor_name = ? AND event_id = ? AND delivered = 1 AND sent_at > ?
)
`

type EventSuppressedParams struct {
	MonitorName string
	EventID     string
	SentAt      int64
}

// Dedupe: was this id delivered within the window?
func (q *Queries) EventSuppressed(ctx context.Context, arg EventSuppressedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventSuppressed, arg.MonitorName, arg.EventID, arg.SentAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEvents = `-- name: ListEvents :many
SELECT monitor_name, event_id, title, summary, url, severity, sent_at, delivered, error FROM events
WHERE monitor_name = ?1
    AND (?2 = 0 OR delivered = 0)
    AND (?3 = 0 OR sent_at >= ?3)
ORDER BY sent_at DESC
LIMIT ?4
`

type ListEventsParams struct {
	MonitorName string
	OnlyFailed  interface{}
	Since       interface{}
	Lim         int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.MonitorName,
		arg.OnlyFailed,
		arg.Since,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.MonitorName,
			&i.EventID,
			&i.Title,
			&i.Summary,
			&i.Url,
			&i.Severity,
			&i.SentAt,
			&i.Delivered,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events WHERE sent_at < ?
`

func (q *Queries) PruneEvents(ctx context.Context, sentAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, sentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEvent = `-- name: UpsertEvent :exec
INSERT INTO events (monitor_name, event_id, title, summary, url, severity, sent_at, delivered, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(monitor_name, event_id) DO UPDATE SET
    title = excluded.title,
    summary = excluded.summary,
    url = excluded.url,
    severity = excluded.severity,
    sent_at = excluded.sent_at,
    delivered = excluded.delivered,
    error = excluded.error
`

type UpsertEventParams struct {
	MonitorName string
	EventID     string
	Title       string
	Summary     string
	Url         string
	Severity    string
	SentAt      int64
	Delivered   int64
	Error       string
}

// One row per (monitor, event_id): each send updates the row's latest state.
func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertEvent,
		arg.MonitorName,
		arg.EventID,
		arg.Title,
		arg.Summary,
		arg.Url,
		arg.Severity,
		arg.SentAt,
		arg.Delivered,
		arg.Error,
	)
	return err
}
