// Code generated by sqlc. DO NOT EDIT.
package db

type ProxyPool struct {
	Name      string
	Strategy  string
	Proxies   string
	Offset    int64
	CreatedAt int64
	UpdatedAt int64
}
type Route struct {
	Name      string
	Kind      string
	Config    string
	CreatedAt int64
	UpdatedAt int64
}
