// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Event struct {
	ID          int64
	MonitorName string
	EventID     string
	Title       string
	Summary     string
	Url         string
	Severity    string
	SentAt      int64
	Delivered   int64
	Error       string
}

type Monitor struct {
	Name                string
	SourceDir           string
	ArtifactDir         string
	BinaryPath          string
	Definition          string
	Status              string
	IntervalMs          int64
	TtlMs               int64
	TimeoutMs           int64
	MaxEvents           int64
	Deliveries          string
	ProxyPool           sql.NullString
	State               string
	StateVersion        int64
	StateRevision       int64
	CreatedAt           int64
	UpdatedAt           int64
	ExpiresAt           sql.NullInt64
	NextDueAt           sql.NullInt64
	LastRunAt           sql.NullInt64
	ExpiredAt           sql.NullInt64
	RunningRunID        string
	RunningStartedAt    sql.NullInt64
	RunningExpiresAt    sql.NullInt64
	LastStatus          string
	NotifiedStatus      string
	ConsecutiveFailures int64
	TotalRuns           int64
	TotalFailures       int64
}

type ProxyPool struct {
	Name      string
	Strategy  string
	Proxies   string
	Offset    int64
	CreatedAt int64
	UpdatedAt int64
}

type Route struct {
	Name      string
	Kind      string
	Config    string
	CreatedAt int64
	UpdatedAt int64
}

type Run struct {
	ID          string
	MonitorName string
	StartedAt   int64
	FinishedAt  int64
	Status      string
	ExitCode    int64
	Stdout      string
	Stderr      string
	Error       string
	Notified    int64
	NotifyError string
}
