// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"
	"database/sql"
)

const advanceMonitor = `-- name: AdvanceMonitor :execrows
UPDATE monitors
SET last_run_at = ?1,
    next_due_at = ?2,
    updated_at = ?1,
    running_run_id = '', running_started_at = NULL, running_expires_at = NULL,
    last_status = ?3,
    consecutive_failures = CASE WHEN ?4 = 1 THEN consecutive_failures + 1 ELSE 0 END,
    total_runs = total_runs + 1,
    total_failures = total_failures + ?4
WHERE name = ?5 AND status = 'active' AND running_run_id = ?6
`

type AdvanceMonitorParams struct {
	FinishedAt sql.NullInt64
	NextDue    sql.NullInt64
	Status     string
	Failed     interface{}
	Name       string
	RunID      string
}

func (q *Queries) AdvanceMonitor(ctx context.Context, arg AdvanceMonitorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceMonitor,
		arg.FinishedAt,
		arg.NextDue,
		arg.Status,
		arg.Failed,
		arg.Name,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimMonitor = `-- name: ClaimMonitor :execrows
UPDATE monitors
SET running_run_id = ?1,
    running_started_at = ?2,
    running_expires_at = ?3,
    next_due_at = ?3,
    updated_at = ?4
WHERE name = ?5
    AND status = 'active'
    AND next_due_at IS NOT NULL
    AND next_due_at <= ?4
    AND (expires_at IS NULL OR expires_at > ?4)
    AND (running_run_id = '' OR running_expires_at IS NULL OR running_expires_at <= ?4)
`

type ClaimMonitorParams struct {
	RunID        string
	StartedAt    sql.NullInt64
	LeaseExpires sql.NullInt64
	Now          int64
	Name         string
}

func (q *Queries) ClaimMonitor(ctx context.Context, arg ClaimMonitorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMonitor,
		arg.RunID,
		arg.StartedAt,
		arg.LeaseExpires,
		arg.Now,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors WHERE name = ?
`

func (q *Queries) DeleteMonitor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteMonitor, name)
	return err
}

const earliestDue = `-- name: EarliestDue :one
SELECT MIN(next_due_at) FROM monitors WHERE status = 'active' AND next_due_at IS NOT NULL
`

func (q *Queries) EarliestDue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, earliestDue)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const expireDueMonitors = `-- name: ExpireDueMonitors :execrows
UPDATE monitors
SET status = 'expired', expired_at = ?1, updated_at = ?1
WHERE status = 'active' AND expires_at IS NOT NULL AND expires_at <= ?1
`

func (q *Queries) ExpireDueMonitors(ctx context.Context, now sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireDueMonitors, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireMonitor = `-- name: ExpireMonitor :execrows
UPDATE monitors
SET status = 'expired', expired_at = ?1, updated_at = ?1
WHERE name = ?2
`

type ExpireMonitorParams struct {
	Now  sql.NullInt64
	Name string
}

func (q *Queries) ExpireMonitor(ctx context.Context, arg ExpireMonitorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireMonitor, arg.Now, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMonitor = `-- name: GetMonitor :one
SELECT name, source_dir, artifact_dir, binary_path, definition, status, interval_ms, ttl_ms, timeout_ms, max_events, deliveries, proxy_pool, state, state_version, state_revision, created_at, updated_at, expires_at, next_due_at, last_run_at, expired_at, running_run_id, running_started_at, running_expires_at, last_status, notified_status, consecutive_failures, total_runs, total_failures FROM monitors WHERE name = ?
`

func (q *Queries) GetMonitor(ctx context.Context, name string) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitor, name)
	var i Monitor
	err := row.Scan(
		&i.Name,
		&i.SourceDir,
		&i.ArtifactDir,
		&i.BinaryPath,
		&i.Definition,
		&i.Status,
		&i.IntervalMs,
		&i.TtlMs,
		&i.TimeoutMs,
		&i.MaxEvents,
		&i.Deliveries,
		&i.ProxyPool,
		&i.State,
		&i.StateVersion,
		&i.StateRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.NextDueAt,
		&i.LastRunAt,
		&i.ExpiredAt,
		&i.RunningRunID,
		&i.RunningStartedAt,
		&i.RunningExpiresAt,
		&i.LastStatus,
		&i.NotifiedStatus,
		&i.ConsecutiveFailures,
		&i.TotalRuns,
		&i.TotalFailures,
	)
	return i, err
}

const listMonitors = `-- name: ListMonitors :many
SELECT name, source_dir, artifact_dir, binary_path, definition, status, interval_ms, ttl_ms, timeout_ms, max_events, deliveries, proxy_pool, state, state_version, state_revision, created_at, updated_at, expires_at, next_due_at, last_run_at, expired_at, running_run_id, running_started_at, running_expires_at, last_status, notified_status, consecutive_failures, total_runs, total_failures FROM monitors ORDER BY name
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.Name,
			&i.SourceDir,
			&i.ArtifactDir,
			&i.BinaryPath,
			&i.Definition,
			&i.Status,
			&i.IntervalMs,
			&i.TtlMs,
			&i.TimeoutMs,
			&i.MaxEvents,
			&i.Deliveries,
			&i.ProxyPool,
			&i.State,
			&i.StateVersion,
			&i.StateRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.NextDueAt,
			&i.LastRunAt,
			&i.ExpiredAt,
			&i.RunningRunID,
			&i.RunningStartedAt,
			&i.RunningExpiresAt,
			&i.LastStatus,
			&i.NotifiedStatus,
			&i.ConsecutiveFailures,
			&i.TotalRuns,
			&i.TotalFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotified = `-- name: MarkNotified :exec
UPDATE monitors SET notified_status = ? WHERE name = ?
`

type MarkNotifiedParams struct {
	NotifiedStatus string
	Name           string
}

func (q *Queries) MarkNotified(ctx context.Context, arg MarkNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, markNotified, arg.NotifiedStatus, arg.Name)
	return err
}

const saveMonitorState = `-- name: SaveMonitorState :execrows
UPDATE monitors
SET state = ?1, state_revision = state_revision + 1
WHERE name = ?2 AND state_revision = ?3
`

type SaveMonitorStateParams struct {
	State    string
	Name     string
	Revision int64
}

func (q *Queries) SaveMonitorState(ctx context.Context, arg SaveMonitorStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveMonitorState, arg.State, arg.Name, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectDueMonitors = `-- name: SelectDueMonitors :many
SELECT name, source_dir, artifact_dir, binary_path, definition, status, interval_ms, ttl_ms, timeout_ms, max_events, deliveries, proxy_pool, state, state_version, state_revision, created_at, updated_at, expires_at, next_due_at, last_run_at, expired_at, running_run_id, running_started_at, running_expires_at, last_status, notified_status, consecutive_failures, total_runs, total_failures FROM monitors
WHERE status = 'active'
    AND next_due_at IS NOT NULL
    AND next_due_at <= ?1
    AND (expires_at IS NULL OR expires_at > ?1)
    AND (running_run_id = '' OR running_expires_at IS NULL OR running_expires_at <= ?1)
ORDER BY next_due_at, name
LIMIT ?2
`

type SelectDueMonitorsParams struct {
	Now sql.NullInt64
	Lim int64
}

func (q *Queries) SelectDueMonitors(ctx context.Context, arg SelectDueMonitorsParams) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, selectDueMonitors, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.Name,
			&i.SourceDir,
			&i.ArtifactDir,
			&i.BinaryPath,
			&i.Definition,
			&i.Status,
			&i.IntervalMs,
			&i.TtlMs,
			&i.TimeoutMs,
			&i.MaxEvents,
			&i.Deliveries,
			&i.ProxyPool,
			&i.State,
			&i.StateVersion,
			&i.StateRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.NextDueAt,
			&i.LastRunAt,
			&i.ExpiredAt,
			&i.RunningRunID,
			&i.RunningStartedAt,
			&i.RunningExpiresAt,
			&i.LastStatus,
			&i.NotifiedStatus,
			&i.ConsecutiveFailures,
			&i.TotalRuns,
			&i.TotalFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMonitorState = `-- name: SetMonitorState :execrows
UPDATE monitors
SET state = ?1, state_version = ?2,
    state_revision = state_revision + 1, updated_at = ?3
WHERE name = ?4
`

type SetMonitorStateParams struct {
	State        string
	StateVersion int64
	UpdatedAt    int64
	Name         string
}

func (q *Queries) SetMonitorState(ctx context.Context, arg SetMonitorStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMonitorState,
		arg.State,
		arg.StateVersion,
		arg.UpdatedAt,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMonitor = `-- name: UpsertMonitor :exec
INSERT INTO monitors (
    name, source_dir, artifact_dir, binary_path, definition, status,
    interval_ms, ttl_ms, timeout_ms, max_events, deliveries, proxy_pool,
    state, state_version, state_revision,
    created_at, updated_at, expires_at, next_due_at, last_run_at, expired_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11, ?12,
    ?13, ?14, ?15,
    ?16, ?17, ?18, ?19, ?20, ?21
)
ON CONFLICT(name) DO UPDATE SET
    source_dir = excluded.source_dir,
    artifact_dir = excluded.artifact_dir,
    binary_path = excluded.binary_path,
    definition = excluded.definition,
    status = excluded.status,
    interval_ms = excluded.interval_ms,
    ttl_ms = excluded.ttl_ms,
    timeout_ms = excluded.timeout_ms,
    max_events = excluded.max_events,
    deliveries = excluded.deliveries,
    proxy_pool = excluded.proxy_pool,
    state = excluded.state,
    state_version = excluded.state_version,
    state_revision = monitors.state_revision + 1,
    updated_at = excluded.updated_at,
    expires_at = excluded.expires_at,
    next_due_at = excluded.next_due_at,
    expired_at = excluded.expired_at,
    running_run_id = '',
    running_started_at = NULL,
    running_expires_at = NULL
`

type UpsertMonitorParams struct {
	Name          string
	SourceDir     string
	ArtifactDir   string
	BinaryPath    string
	Definition    string
	Status        string
	IntervalMs    int64
	TtlMs         int64
	TimeoutMs     int64
	MaxEvents     int64
	Deliveries    string
	ProxyPool     sql.NullString
	State         string
	StateVersion  int64
	StateRevision int64
	CreatedAt     int64
	UpdatedAt     int64
	ExpiresAt     sql.NullInt64
	NextDueAt     sql.NullInt64
	LastRunAt     sql.NullInt64
	ExpiredAt     sql.NullInt64
}

func (q *Queries) UpsertMonitor(ctx context.Context, arg UpsertMonitorParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonitor,
		arg.Name,
		arg.SourceDir,
		arg.ArtifactDir,
		arg.BinaryPath,
		arg.Definition,
		arg.Status,
		arg.IntervalMs,
		arg.TtlMs,
		arg.TimeoutMs,
		arg.MaxEvents,
		arg.Deliveries,
		arg.ProxyPool,
		arg.State,
		arg.StateVersion,
		arg.StateRevision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.NextDueAt,
		arg.LastRunAt,
		arg.ExpiredAt,
	)
	return err
}
