// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_pools.sql

package db

import "context"

const deleteProxyPool = `-- name: DeleteProxyPool :exec
DELETE FROM proxy_pools WHERE name = ?
`

func (q *Queries) DeleteProxyPool(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProxyPool, name)
	return err
}

const getProxyOffset = `-- name: GetProxyOffset :one
SELECT offset FROM proxy_pools WHERE name = ?
`

func (q *Queries) GetProxyOffset(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProxyOffset, name)
	var offset int64
	err := row.Scan(&offset)
	return offset, err
}

const getProxyPool = `-- name: GetProxyPool :one
SELECT name, strategy, proxies, "offset", created_at, updated_at FROM proxy_pools WHERE name = ?
`

func (q *Queries) GetProxyPool(ctx context.Context, name string) (ProxyPool, error) {
	row := q.db.QueryRowContext(ctx, getProxyPool, name)
	var i ProxyPool
	err := row.Scan(
		&i.Name,
		&i.Strategy,
		&i.Proxies,
		&i.Offset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyPools = `-- name: ListProxyPools :many
SELECT name, strategy, proxies, "offset", created_at, updated_at FROM proxy_pools ORDER BY name
`

func (q *Queries) ListProxyPools(ctx context.Context) ([]ProxyPool, error) {
	rows, err := q.db.QueryContext(ctx, listProxyPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyPool{}
	for rows.Next() {
		var i ProxyPool
		if err := rows.Scan(
			&i.Name,
			&i.Strategy,
			&i.Proxies,
			&i.Offset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProxyOffset = `-- name: SetProxyOffset :exec
UPDATE proxy_pools SET offset = ?, updated_at = ? WHERE name = ?
`

type SetProxyOffsetParams struct {
	Offset    int64
	UpdatedAt int64
	Name      string
}

func (q *Queries) SetProxyOffset(ctx context.Context, arg SetProxyOffsetParams) error {
	_, err := q.db.ExecContext(ctx, setProxyOffset, arg.Offset, arg.UpdatedAt, arg.Name)
	return err
}

const upsertProxyPool = `-- name: UpsertProxyPool :exec
INSERT INTO proxy_pools (name, strategy, proxies, offset, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    strategy = excluded.strategy,
    proxies = excluded.proxies,
    updated_at = excluded.updated_at
`

type UpsertProxyPoolParams struct {
	Name      string
	Strategy  string
	Proxies   string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertProxyPool(ctx context.Context, arg UpsertProxyPoolParams) error {
	_, err := q.db.ExecContext(ctx, upsertProxyPool,
		arg.Name,
		arg.Strategy,
		arg.Proxies,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
