// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetRoute(ctx context.Context, name string) (Route, error)
	ListRoutes(ctx context.Context) ([]Route, error)
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
}

var _ Querier = (*Queries)(nil)
