// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdvanceMonitor(ctx context.Context, arg AdvanceMonitorParams) (int64, error)
	ClaimMonitor(ctx context.Context, arg ClaimMonitorParams) (int64, error)
	CountMonitorsUsingPool(ctx context.Context, proxyPool sql.NullString) (int64, error)
	DeleteMonitor(ctx context.Context, name string) error
	DeleteProxyPool(ctx context.Context, name string) error
	EarliestDue(ctx context.Context) (interface{}, error)
	// Dedupe: was this id delivered within the window?
	EventSuppressed(ctx context.Context, arg EventSuppressedParams) (bool, error)
	ExpireDueMonitors(ctx context.Context, now sql.NullInt64) (int64, error)
	ExpireMonitor(ctx context.Context, arg ExpireMonitorParams) (int64, error)
	GetMonitor(ctx context.Context, name string) (Monitor, error)
	GetProxyOffset(ctx context.Context, name string) (int64, error)
	GetProxyPool(ctx context.Context, name string) (ProxyPool, error)
	GetRoute(ctx context.Context, name string) (Route, error)
	GetRun(ctx context.Context, id string) (Run, error)
	InsertRun(ctx context.Context, arg InsertRunParams) error
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListMonitors(ctx context.Context) ([]Monitor, error)
	ListProxyPools(ctx context.Context) ([]ProxyPool, error)
	ListRoutes(ctx context.Context) ([]Route, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error)
	MarkNotified(ctx context.Context, arg MarkNotifiedParams) error
	PruneEvents(ctx context.Context, sentAt int64) (int64, error)
	PruneRunsBefore(ctx context.Context, arg PruneRunsBeforeParams) error
	SaveMonitorState(ctx context.Context, arg SaveMonitorStateParams) (int64, error)
	SelectDueMonitors(ctx context.Context, arg SelectDueMonitorsParams) ([]Monitor, error)
	SetMonitorState(ctx context.Context, arg SetMonitorStateParams) (int64, error)
	SetProxyOffset(ctx context.Context, arg SetProxyOffsetParams) error
	UpdateRunNotification(ctx context.Context, arg UpdateRunNotificationParams) (int64, error)
	// One row per (monitor, event_id): each send updates the row's latest state.
	UpsertEvent(ctx context.Context, arg UpsertEventParams) error
	UpsertMonitor(ctx context.Context, arg UpsertMonitorParams) error
	UpsertProxyPool(ctx context.Context, arg UpsertProxyPoolParams) error
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
}

var _ Querier = (*Queries)(nil)
