// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const getRoute = `-- name: GetRoute :one
SELECT name, kind, config, created_at, updated_at FROM routes WHERE name = ?
`

func (q *Queries) GetRoute(ctx context.Context, name string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, name)
	var i Route
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT name, kind, config, created_at, updated_at FROM routes ORDER BY name
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoute = `-- name: UpsertRoute :exec
INSERT INTO routes (name, kind, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    kind = excluded.kind,
    config = excluded.config,
    updated_at = excluded.updated_at
`

type UpsertRouteParams struct {
	Name      string
	Kind      string
	Config    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoute,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
