// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
)

const getRun = `-- name: GetRun :one
SELECT id, monitor_name, started_at, finished_at, status, exit_code, stdout, stderr, error, notified, notify_error FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MonitorName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ExitCode,
		&i.Stdout,
		&i.Stderr,
		&i.Error,
		&i.Notified,
		&i.NotifyError,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (
    id, monitor_name, started_at, finished_at, status, exit_code,
    stdout, stderr, error, notified, notify_error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRunParams struct {
	ID          string
	MonitorName string
	StartedAt   int64
	FinishedAt  int64
	Status      string
	ExitCode    int64
	Stdout      string
	Stderr      string
	Error       string
	Notified    int64
	NotifyError string
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun,
		arg.ID,
		arg.MonitorName,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.Error,
		arg.Notified,
		arg.NotifyError,
	)
	return err
}

const listRuns = `-- name: ListRuns :many
SELECT id, monitor_name, started_at, finished_at, status, exit_code, stdout, stderr, error, notified, notify_error FROM runs
WHERE monitor_name = ?1
    AND (?2 = 0 OR status = 'failure')
ORDER BY started_at DESC
LIMIT ?3
`

type ListRunsParams struct {
	MonitorName string
	OnlyFailed  interface{}
	Lim         int64
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.MonitorName, arg.OnlyFailed, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.MonitorName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.ExitCode,
			&i.Stdout,
			&i.Stderr,
			&i.Error,
			&i.Notified,
			&i.NotifyError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunNotification = `-- name: UpdateRunNotification :execrows
UPDATE runs SET notified = ?, notify_error = ? WHERE id = ?
`

type UpdateRunNotificationParams struct {
	Notified    int64
	NotifyError string
	ID          string
}

func (q *Queries) UpdateRunNotification(ctx context.Context, arg UpdateRunNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunNotification, arg.Notified, arg.NotifyError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
